[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo= 'lambdalisue/fern.vim'

# 自動的に閉じ括弧を挿入
[[plugins]]
repo = 'Townk/vim-autoclose' 

# ctags,tabbar
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
filetype on
'''

# Ruby reference(refe2) viewer
[[plugins]]
repo = 'thinca/vim-ref'

# Markdown
[[plugins]]
repo =  'godlygeek/tabular'
[[plugins]]
repo =  'tpope/vim-markdown'
[[plugins]]
repo =  'previm/previm'
hook_add = '''
let g:previm_open_cmd = 'open'
'''

# Twitter client
[[plugins]]
repo = 'twitvim/twitvim'
hook_add = '''
let twitvim_enable_python = 1
let twitvim_count = 50
let g:twitvim_browser_cmd = 'open'
'''

# XML
[[plugins]]
repo = 'othree/xml.vim'

# Vdebug
[[plugins]]
# DBGP(Common DeBugGer Protocol as used by Xdebug) client
repo = 'joonty/vdebug'

# ruby, rails
# if, do def等を自動で閉じる
[[plugins]]
repo = 'tpope/vim-endwise'
repo = 'tpope/vim-rails'


# git, GitHub
# ブラウザ
[[plugins]]
repo = 'cohama/agit.vim' 
[[plugins]]
# GitHubの絵文字,issue番号,リポジトリ名etcの補完
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
" カーソル下のURIをブラウザで表示
nmap <Leader>bo <Plug>(openbrowser-open)
vmap <Leader>bo <Plug>(openbrowser-open)
" カーソル下の文字列をぐぐる
nmap <Leader>bs <Plug>(openbrowser-smart-search)
vmap <Leader>bs <Plug>(openbrowser-smart-search)
'''

# tableを記述/整形
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_denite = 1
nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
'''

[[plugins]]
repo = 'vim-scripts/openssl.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
let g:calendar_google_calendar = 1
let g:calendar_views = ['year','month','weekday','day','clock']
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
" PHP
if executable('intelephense')
	autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'intelephense',
		\ 'cmd': {server_info->['node', expand('$NVM_BIN/intelephense'), '--stdio']},
		\ 'initialization_options': {"storagePath": '/tmp/intelephense'},
		\ 'whitelist': ['php'],
		\ })
endif
" Ruby 
if executable('solargraph')
	autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'solargraph',
		\ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
		\ 'initialization_options': {"diagnostics": "true"},
		\ 'whitelist': ['ruby'],
		\ })
endif

" Go
if executable('gopls')
	augroup LspGo
		au!
		autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'go-lang',
		\ 'cmd': {server_info->['gopls']},
		\ 'whitelist':['go'],
		\})
		autocmd FileType go setlocal omnifunc=lsp#complete
		autocmd FileType go nmap <buffer> <Leader>gd <plug>(lsp-definition)
		autocmd FileType go nmap <buffer> <Leader>gdd <plug>(lsp-document-diagnostics)
		autocmd FileType go nmap <buffer> <Leader>gn <plug>(lsp-next-error)
		autocmd FileType go nmap <buffer> <Leader>gp <plug>(lsp-previous-error)
		autocmd FileType go nmap <buffer> <Leader>gr <plug>(lsp-references)
	augroup END
endif

let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursol = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '!!'}

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:lsp_settings_filetype_javascript = ['typescript-language-server','eslint-language-server']
'''
