[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# 自動的に閉じ括弧を挿入
[[plugins]]
repo = 'Townk/vim-autoclose' 

# ctags,tabbar
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
filetype on
'''

# Ruby reference(refe2) viewer
[[plugins]]
repo = 'thinca/vim-ref'

# Markdown
[[plugins]]
repo =  'godlygeek/tabular'
[[plugins]]
repo =  'tpope/vim-markdown'
[[plugins]]
repo =  'previm/previm'
hook_add = '''
let g:previm_open_cmd = 'open'
'''

# Twitter client
[[plugins]]
repo = 'twitvim/twitvim'
hook_add = '''
let twitvim_enable_python = 1
let twitvim_count = 50
let g:twitvim_browser_cmd = 'open'
'''

# XML
[[plugins]]
repo = 'othree/xml.vim'

# Vdebug
[[plugins]]
# DBGP(Common DeBugGer Protocol as used by Xdebug) client
repo = 'joonty/vdebug'

# ruby, rails
# if, do def等を自動で閉じる
[[plugins]]
repo = 'tpope/vim-endwise'
repo = 'tpope/vim-rails'


# git, GitHub
# ブラウザ
[[plugins]]
repo = 'cohama/agit.vim' 
[[plugins]]
# GitHubの絵文字,issue番号,リポジトリ名etcの補完
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
" カーソル下のURIをブラウザで表示
nmap <Leader>bo <Plug>(openbrowser-open)
vmap <Leader>bo <Plug>(openbrowser-open)
" カーソル下の文字列をぐぐる
nmap <Leader>bs <Plug>(openbrowser-smart-search)
vmap <Leader>bs <Plug>(openbrowser-smart-search)
'''

# tableを記述/整形
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
'''

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_denite = 1
nnoremap <Leader>mn  :MemoNew<CR>
nnoremap <Leader>ml  :MemoList<CR>
'''

[[plugins]]
repo = 'vim-scripts/openssl.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
let g:calendar_google_calendar = 1
let g:calendar_views = ['year','month','weekday','day','clock']
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
" Ruby 
if executable('solargraph')
	autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'solargraph',
		\ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
		\ 'initialization_options': {"diagnostics": "true"},
		\ 'whitelist': ['ruby'],
		\ })
endif

let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursol = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '!!'}

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
	setlocal omnifunc=lsp#complete
	nmap <buffer> <Leader>gd <plug>(lsp-definition) " 宣言元にジャンプ
  nmap <buffer> <Leader>gs <plug>(lsp-document-symbol-search) " シンボル検索
  nmap <buffer> <Leader>gS <plug>(lsp-workspace-symbol-search) " プロジェクト内をシンボル検索
  nmap <buffer> <Leader>gr <plug>(lsp-references) " バッファ内を検索
	nmap <buffer> <Leader>gdd <plug>(lsp-document-diagnostics) " コード診断
	nmap <buffer> <Leader>gn <plug>(lsp-next-error)
	nmap <buffer> <Leader>gp <plug>(lsp-previous-error)
	nmap <buffer> <Leader>gr <plug>(lsp-references)
  nmap <buffer> <Leader>k <plug>(lsp-hover)
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:lsp_settings_filetype_javascript = ['typescript-language-server','eslint-language-server']
'''

# ファイラ 
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
rev = 'main'
hook_add = '''
let g:fern#default_hidden=1
let g:fern#renderer = "nerdfont"
function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction
augroup __fern__
  au!
  autocmd VimEnter * ++nested Fern . -drawer -stay -keep -toggle -reveal=%
  autocmd FileType fern call s:fern_settings()
augroup END
nnoremap  <Leader>t :<c-u>Fern . -drawer -stay -keep -toggle -reveal=%<cr>
'''

# font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
hook_add = '''
set guifont=DroidSansMono_Nerd_Font:h11
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
nmap <c-e> <plug>(ctrlp-launcher)
'''

[[plugins]]
repo = 'mattn/ctrlp-matchfuzzy'

[[plugins]]
repo = 'mattn/ctrlp-launcher'

[[plugins]]
repo = 'mattn/ctrlp-lsp'

[[plugins]]
repo = 'mattn/ctrlp-git'

# ChatGPT
[[plugins]]
repo = 'madox2/vim-ai'

[[plugins]]
repo = 'github/copilot.vim'
