[[plugin]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
autocmd Tlist
let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
nnoremap <Leader>tl :Tlist<CR>
'''

# ES2015, node.js, JSON
[[plugins]]
repo = 'othree/yajs.vim'
#hook_add = '''
#autocmd FileType javascript
#'''
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/denite.rc.vim'
hook_add = '''
" カレントディレクトリをgrep
nnoremap <silent> <Leader>g :<C-u>Denite grep:.<CR>
nnoremap <silent> <Leader>cg :<C-u>DeniteCursorWord grep:.<CR>
" バッファ一覧を表示
nnoremap <silent> <Leader>ub :<C-u>Denite buffer<CR>
" 対象ファイルのカレントディレクトリ ファイル一覧を表示
nnoremap <silent> <Leader>uf :<C-u>DeniteBufferDir file/rec<CR>
" レジスタ一覧
nnoremap <silent> <Leader>ur :<C-u>Denite -buffer-name=register register<CR>
" ghqでリポジトリ一覧にアクセス
nnoremap <silent> <Leader>gh :<C-u>Denite ghq<CR>
" denite-gitでgit操作
nnoremap <silent> gi :<C-u>Denite gitstatus<CR>
nnoremap <silent> gib :<C-u>Denite gitbranch<CR>
nnoremap <silent> gil :<C-u>Denite gitlog<CR>
'''

[[plugins]]
repo = 'neoclide/denite-git'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends =  ['neosnippet-snippets']
hook_source = '''
let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#enable_completed_snippet = 1
let g:neosnippet#expand_word_boundary = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
hook_source = '''
call asyncomplete#register_source(asyncomplete#sources#neosnippet#get_source_options({
	\ 'name': 'neosnippet',
	\ 'whitelist': ['php','ruby','go'],
	\ 'completor': function('asyncomplete#sources#neosnippet#completor'),
	\ }))

" 特定のファイルタイプのファイルのみ補完対象とする
let g:asyncomplate_enable_for_all = 0
autocmd vimrc FileType php,ruby,go,
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['php','ruby','go']
depends = ['asyncomplete.vim', 'vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_source = '''
let g:asyncomplete_log_file = expand('~/asyncomplete.log')
'''

# golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
" gofmt時にインポートするパッケージを整理
let g:go_fmt_command = "goimports"
let g:go_fmt_options = {
	\ 'goimports': '-local vcs.mediba.jp',
	\ }
" go run
"au FileType go nmap <Leader>gr <Plug>(go-run)
" go test
au FileType go nmap <Leader>gt <Plug>(go-test)
" Show the relevant GoDoc for the word under the cursor in a split window.
au FileType go nmap <Leader>gdt <Plug>(go-doc-split)
" Calls `golint` for the current package
au FileType go nmap <Leader>gl <Plug>(go-lint)
" Calls `go vet` for the current package
au FileType go nmap <Leader>gv <Plug>(go-vet)
'''
