[[plugin]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
autocmd Tlist
let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
nnoremap <Leader>tl :Tlist<CR>
'''

# ES2015, node.js, JSON
[[plugins]]
repo = 'othree/yajs.vim'
#hook_add = '''
#autocmd FileType javascript
#'''
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'elzr/vim-json'

