[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'scrooloose/nerdtree' 

# 自動的に閉じ括弧を挿入
[[plugins]]
repo = 'Townk/vim-autoclose' 

# ctags,tabbar
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
filetype on
'''

# Ruby reference(refe2) viewer
[[plugins]]
repo = 'thinca/vim-ref'

# Markdown
[[plugins]]
repo =  'godlygeek/tabular'
[[plugins]]
repo =  'tpope/vim-markdown'
[[plugins]]
repo =  'previm/previm'
hook_add = '''
let g:previm_open_cmd = 'open'
'''

# Twitter client
[[plugins]]
repo = 'twitvim/twitvim'
hook_add = '''
let twitvim_enable_python = 1
let twitvim_count = 50
let g:twitvim_browser_cmd = 'open'
'''

# XML
[[plugins]]
repo = 'othree/xml.vim'

# golang
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
" go run
au FileType go nmap <Leader>gr <Plug>(go-run)
" go test
au FileType go nmap <Leader>gt <Plug>(go-test)
" Show the relevant GoDoc for the word under the cursor in a split window.
au FileType go nmap <Leader>gdt <Plug>(go-doc-split)
'''
# Vdebug
[[plugins]]
# DBGP(Common DeBugGer Protocol as used by Xdebug) client
repo = 'joonty/vdebug'

# ruby, rails
# if, do def等を自動で閉じる
[[plugins]]
repo = 'tpope/vim-endwise'
repo = 'tpope/vim-rails'


# git, GitHub
# ブラウザ
[[plugins]]
repo = 'cohama/agit.vim' 
[[plugins]]
# GitHubの絵文字,issue番号,リポジトリ名etcの補完
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
" カーソル下のURIをブラウザで表示
nmap ,bo <Plug>(openbrowser-open)
vmap ,bo <Plug>(openbrowser-open)
" カーソル下の文字列をぐぐる
nmap ,bs <Plug>(openbrowser-smart-search)
vmap ,bs <Plug>(openbrowser-smart-search)
'''

# tableを記述/整形
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
'''

[[plugins]]
repo = 'glidenote/memolist.vim'

# ALE(Asynchronous Lint Engine)
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_emit_conflict_warnings = 0
'''

[[plugins]]
repo = 'vim-scripts/openssl.vim'

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
let g:calendar_google_calendar = 1
let g:calendar_views = ['year','month','weekday','day','clock']
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
" PHP
if executable('intelephense')
	autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'intelephense',
		\ 'cmd': {server_info->['node', expand('$NVM_BIN/intelephense'), '--stdio']},
		\ 'initialization_options': {"storagePath": '/tmp/intelephense'},
		\ 'whitelist': ['php'],
		\ })
endif
" Ruby 
if executable('solargraph')
	autocmd User lsp_setup call lsp#register_server({
		\ 'name': 'solargraph',
		\ 'cmd': {server_info->[&shell, &shellcmdflag, 'solargraph stdio']},
		\ 'initialization_options': {"diagnostics": "true"},
		\ 'whitelist': ['ruby'],
		\ })
endif
let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursol = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '!!'}

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
'''
