[[plugin]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
autocmd Tlist
let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
nnoremap <Leader>tl :Tlist<CR>
'''

# ES2015, node.js, JSON
[[plugins]]
repo = 'othree/yajs.vim'
#hook_add = '''
#autocmd FileType javascript
#'''
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
	nnoremap <silent> ,g :<C-u>Denite -buffer-name=search
		\ -no-empty -mode=normal grep<CR>
	nnoremap <silent> ,cg :<C-u>Denite -buffer-name=search
		\ -no-empty -mode=normal grep<CR><C-R><C-W>
	" バッファ一覧
	nnoremap <silent> ,db :<C-u>Denite -buffer-name=search<CR>
	" ファイル一覧
	nnoremap <silent> ,df :<C-u>Denite -buffer-name=files file<CR>
	" レジスタ一覧
	nnoremap <silent> ,dr :<C-u>Denite -buffer-name=register register<CR>
'''
