[[plugin]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
autocmd Tlist
let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
nnoremap <Leader>tl :Tlist<CR>
'''

# ES2015, node.js, JSON
[[plugins]]
repo = 'othree/yajs.vim'
#hook_add = '''
#autocmd FileType javascript
#'''
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/denite.rc.vim'
hook_add = '''
" カレントディレクトリをgrep
nnoremap <silent> ,g :<C-u>Denite grep:.<CR>
nnoremap <silent> ,cg :<C-u>DeniteCursorWord grep:.<CR>
" バッファ一覧を表示
nnoremap <silent> ,ub :<C-u>Denite buffer<CR>
" 対象ファイルのカレントディレクトリ ファイル一覧を表示
nnoremap <silent> ,uf :<C-u>DeniteBufferDir file/rec<CR>
" レジスタ一覧
nnoremap <silent> ,ur :<C-u>Denite -buffer-name=register register<CR>
" ghqでリポジトリ一覧にアクセス
nnoremap <silent> ,gh :<C-u>Denite ghq<CR>
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends =  ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
hook_source = '''
call asyncomplete#register_source(asyncomplete#sources#neosnippet#get_source_options({
	\ 'name': 'neosnippet',
	\ 'whitelist': ['php'],
	\ 'completor': function('asyncomplete#sources#neosnippet#completor'),
	\ }))

" 特定のファイルタイプのファイルのみ補完対象とする
let g:asyncomplate_enable_for_all = 0
autocmd vimrc FileType php
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['php']
depends = ['asyncomplete.vim', 'vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_source = '''
let g:asyncomplete_log_file = expand('~/asyncomplete.log')
'''
