[[plugin]]
repo = 'vim-scripts/taglist.vim'
hook_add = '''
autocmd Tlist
let Tlist_Use_Right_Window = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
nnoremap <Leader>tl :Tlist<CR>
'''

# ES2015, node.js, JSON
[[plugins]]
repo = 'othree/yajs.vim'
#hook_add = '''
#autocmd FileType javascript
#'''
[[plugins]]
repo = 'moll/vim-node'
[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/rc/denite.rc.vim'
hook_add = '''
" カレントディレクトリをgrep
nnoremap <silent> ,g :<C-u>Denite grep:.<CR>
nnoremap <silent> ,cg :<C-u>DeniteCursorWord grep:.<CR>
" バッファ一覧を表示
nnoremap <silent> ,ub :<C-u>Denite buffer<CR>
" 対象ファイルのカレントディレクトリ ファイル一覧を表示
nnoremap <silent> ,uf :<C-u>DeniteBufferDir file/rec<CR>
" レジスタ一覧
nnoremap <silent> ,ur :<C-u>Denite -buffer-name=register register<CR>
" ghqでリポジトリ一覧にアクセス
nnoremap <silent> [Window]g :<C-u>Denite ghq<CR>
'''

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'
